In [1]:
import numpy as np
import pandas as pd

In [25]:
raw = r'''CC & 8.0 & 8.0 & 8.6 & 8.6 \\
Chipset & GA100 & GA100 & GA102 & GA102 \\
Boost Clock (MHz) & 1440 & 1410 & 1900 & 1740 \\
Memory Clock (MHz) & 1215 & 1215 & 1219 & 1812 \\
Bandwidth (GB/s) & 933.1 & 1560 & 936.2 & 695.8 \\
SMs Count & 56 & 108 & 82 & 84 \\
Core Count & 3584 & 6912 & 10496 & 10752 \\
L1 Cache (KB per SM) & 192 & 192 & 128 & 128 \\
L2 Cache (MB) & 24 & 40 & 6 & 6 \\
VRAM (GB) & 24 & 64 & 24 & 48 \\
TDP (W) & 165 & 400 & 350 & 300 \\
FP32 (TFLOPS) & 10.32 & 19.49 & 35.58 & 37.42'''

In [26]:
parsed = [[r.strip() for r in rr.split('&')] for rr in raw.split(r'\\')]
parsed

[['CC', '8.0', '8.0', '8.6', '8.6'],
 ['Chipset', 'GA100', 'GA100', 'GA102', 'GA102'],
 ['Boost Clock (MHz)', '1440', '1410', '1900', '1740'],
 ['Memory Clock (MHz)', '1215', '1215', '1219', '1812'],
 ['Bandwidth (GB/s)', '933.1', '1560', '936.2', '695.8'],
 ['SMs Count', '56', '108', '82', '84'],
 ['Core Count', '3584', '6912', '10496', '10752'],
 ['L1 Cache (KB per SM)', '192', '192', '128', '128'],
 ['L2 Cache (MB)', '24', '40', '6', '6'],
 ['VRAM (GB)', '24', '64', '24', '48'],
 ['TDP (W)', '165', '400', '350', '300'],
 ['FP32 Performance (TFLOPS)', '10.32', '19.49', '35.58', '37.42']]

In [27]:
df = pd.DataFrame(parsed, columns=['', 'A30', 'A100', 'RTX 3090', 'A40'])
df.set_index(df.columns[0], inplace=True)
df

                             A30   A100 RTX 3090    A40

CC                           8.0    8.0      8.6    8.6
Chipset                    GA100  GA100    GA102  GA102
Boost Clock (MHz)           1440   1410     1900   1740
Memory Clock (MHz)          1215   1215     1219   1812
Bandwidth (GB/s)           933.1   1560    936.2  695.8
SMs Count                     56    108       82     84
Core Count                  3584   6912    10496  10752
L1 Cache (KB per SM)         192    192      128    128
L2 Cache (MB)                 24     40        6      6
VRAM (GB)                     24     64       24     48
TDP (W)                      165    400      350    300
FP32 Performance (TFLOPS)  10.32  19.49    35.58  37.42

In [28]:
A2000mobile = ['8.6', 'GA107', '1687', '1500', '192', '20', '2560', '128', '2', '4', '95', '8.637']
RTX3060mobile = ['8.6', 'GA106', '1425', '1750', '336', '30', '3840', '128', '3', '6', '80', '10.94']

In [29]:
df['RTX3060'] = RTX3060mobile
df['A2000'] = A2000mobile
df2 = df.T

In [32]:
df2['Platform'] = ['Server', 'HPC', 'Desktop', 'Server', 'Mobile', 'Mobile']
df2

,CC,Chipset,Boost Clock (MHz),Memory Clock (MHz),Bandwidth (GB/s),SMs Count,Core Count,L1 Cache (KB per SM),L2 Cache (MB),VRAM (GB),TDP (W),FP32 Performance (TFLOPS),Platform
A30,8.0,GA100,1440,1215,933.1,56,3584,192,24,24,165,10.32,Server
A100,8.0,GA100,1410,1215,1560,108,6912,192,40,64,400,19.49,Server
RTX 3090,8.6,GA102,1900,1219,936.2,82,10496,128,6,24,350,35.58,Desktop
A40,8.6,GA102,1740,1812,695.8,84,10752,128,6,48,300,37.42,Server
RTX3060,8.6,GA106,1425,1750,336,30,3840,128,3,6,80,10.94,Mobile
A2000,8.6,GA107,1687,1500,192,20,2560,128,2,4,95,8.637,Mobile

In [34]:
print(df2.T.to_latex())

\begin{tabular}{lllllll}
\toprule
 & A30 & A100 & RTX 3090 & A40 & RTX3060 & A2000 \\
 &  &  &  &  &  &  \\
\midrule
CC & 8.0 & 8.0 & 8.6 & 8.6 & 8.6 & 8.6 \\
Chipset & GA100 & GA100 & GA102 & GA102 & GA106 & GA107 \\
Boost Clock (MHz) & 1440 & 1410 & 1900 & 1740 & 1425 & 1687 \\
Memory Clock (MHz) & 1215 & 1215 & 1219 & 1812 & 1750 & 1500 \\
Bandwidth (GB/s) & 933.1 & 1560 & 936.2 & 695.8 & 336 & 192 \\
SMs Count & 56 & 108 & 82 & 84 & 30 & 20 \\
Core Count & 3584 & 6912 & 10496 & 10752 & 3840 & 2560 \\
L1 Cache (KB per SM) & 192 & 192 & 128 & 128 & 128 & 128 \\
L2 Cache (MB) & 24 & 40 & 6 & 6 & 3 & 2 \\
VRAM (GB) & 24 & 64 & 24 & 48 & 6 & 4 \\
TDP (W) & 165 & 400 & 350 & 300 & 80 & 95 \\
FP32 Performance (TFLOPS) & 10.32 & 19.49 & 35.58 & 37.42 & 10.94 & 8.637 \\
Platform & Server & Server & Desktop & Server & Mobile & Mobile \\
\bottomrule
\end{tabular}